package api

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"        // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger"    // gin-swagger middleware
	_ "github.com/umarquez/goai_transcriber/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/umarquez/goai_transcriber/internal/controller"
)

// @title GoAI Transcriber API
// @version 1.0
// @description This is a sample server for transcribing audio files.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8080
// @BasePath /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

type Api struct {
	TranscriptionController *controller.TranscriptionController
}

func NewApi(transcriptionController *controller.TranscriptionController) *Api {
	return &Api{TranscriptionController: transcriptionController}
}

func (a *Api) Run() error {
	router := gin.Default()
	router.POST("/transcribe", a.TranscriptionController.Transcribe)

	// Swagger documentation route
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return router.Run(":8080")
}
